---
title: "非類固醇類抗炎藥（NSAID）與低劑量阿司匹林聯用可升高上消化道出血（UGIB）風險"
author: "許sir"

---

### [.設定所需的函式庫(libraries)以及載入資料]
```{r message=FALSE, warning=FALSE}
setwd("D:/Rdata Practice/Health Database")
system.time(load("D:/Rdata Practice/Health Database/ugicco.rda"))

mysample1 <- ugicco[ sample( which(ugicco$ugic==0), round(0.2*length(which(ugicco$ugic==0)))), ]
mysample2 <- ugicco[ sample( which(ugicco$ugic==1), round(0.2*length(which(ugicco$ugic==1)))), ]
mysample <- rbind(mysample1, mysample2)

library(survival)
```

## [第一部份].Kaplan-Meier method
```{r message=FALSE, warning=FALSE}
#library(survival)
mysample$dur <- as.numeric(as.Date(mysample$end.date, "%Y%m%d") - as.Date(mysample$first.date, "%Y%m%d") + 1) / 365.25

surv1 <- survfit(Surv(dur, ugic) ~ 1, conf.type="none", data=mysample)
# surv1 <- survfit(Surv(dur, ugic==1) ~ 1, conf.type="none", data=mysample)
surv1; # summary(surv1)
summary(surv1, times=seq(0, 5, 1))
plot(surv1, xlab="Time", ylab="Survival Probability")
plot(surv1, xlab="Time", ylab="Survival Probability", ylim=c(0.8,1), mark.time=F)

surv2 <- survfit(Surv(dur, ugic) ~ expose, data = mysample)
plot(surv2, xlab="Time", ylab="Survival Probability", col=c(1,2))

survdiff(Surv(dur, ugic) ~ expose, data = mysample, rho=0)
survdiff(Surv(dur, ugic) ~ expose, data = mysample, rho=1)

# With 'rho = 0' this is the log-rank or Mantel-Haenszel test, and with 'rho = 1' it is equivalent to the Peto & Peto modification of the Gehan-Wilcoxon test."
```

## [第一部份].Cox proportional hazards
```{r message=FALSE, warning=FALSE}
coxph1 <- coxph(Surv(dur, ugic) ~ expose, data = mysample)
coxph1
summary(coxph1)

coxph2 <- coxph(Surv(dur, ugic) ~ expose + age + id.sex, data = mysample)
coxph2
summary(coxph2)
# 非類固醇類抗炎藥（NSAID）與低劑量阿司匹林聯用可升高上消化道出血（UGIB）風險

(mytable <- xtabs(~ expose + ugic, data=mysample))
prop.table(mytable, 2)
aggregate(mysample$dur, by=list(Group=mysample$expose), summary)
```

